#!/usr/bin/env sh
usage() {
    echo "usage: $0 PERCENTAGE"
    echo "A wrapper that calls \`brightnessctl set PERCENTAGE%\`. Zero sets minimum backlight instead of no backlight."
}

[ -z "$1" ] && { usage; exit 1; }
[ "$1" -eq "$1" ] || { echo "Not a number"; exit 2; }
[ "$1" -eq 0 ] && { brightnessctl set 1; exit 0; }
brightnessctl set "$1"%

