#!/usr/bin/env bash
sed -Ei '/@darktheme/ {s/^# //}; /@lighttheme/ {s/^([^#])/# \1/}' \
    "$XDG_CONFIG_HOME/alacritty/alacritty.toml" \
    "$XDG_CONFIG_HOME/helix/config.toml"
lookandfeeltool --keep-auto --apply org.kde.breezedark.desktop
pkill -USR1 hx
