#!/usr/bin/env bash


choices=( suspend hibernate poweroff reboot logout )
choice="$(IFS=$'\n'; dmenu-provider -p "See you next time." <<< "${choices[*]}")"

case "$choice" in
    suspend|hibernate|poweroff|reboot) systemctl "$choice";;
    # XXX: can add more, there is like loginctl terminate-session but how do I know it is mine and if it is correct
    logout) bspwm quit; i3-msg exit;;
esac
