#!/usr/bin/env bash
# XXX: chown / chmod HAVE AN -R FLAG, USE THAT INSTEAD.
# I have no idea why I wrote this...
set -euo pipefail

usage() {
  echo "usage: $0 [-dfsh] [-o username]"
  echo "crudely fixes some file attributes that were messed up by copying to other disk/ntfs. Literally just mnemonic find -exec."
  echo "-o     set ownership to username"
  echo "-d     set all dir perms to 755"
  echo "-f     set all regular file perms to 644"
  echo "-s     set all regular file perms to 755 (assume they are scripts)"
  echo "-h     help"
}

refuse_stupid_dirs()
{
  case "$PWD" in
  /|/home|/etc|/usr/bin|/usr/lib|/var|/bin|/lib)
    echo "Refusing to clobber system directories."; exit 1;;
  esac 
}

main()
{

  [ -z "$*" ] && { usage; exit 0; }

  getopt_result=$(getopt -o o:dfsh --long ownership:,dirperms,fileperms,scriptperms,help -- "$@")
  # if [ $? != 0 ] ; then echo "getopt failed, exiting." >&2 ; exit 1 ; fi
  eval set -- "$getopt_result"

  [ "$#" = 0 ] && { usage; exit 0; };

  while true; do
    [ "$#" = 0 ] && break;

    case "$1" in
      -o|--ownership)
        refuse_stupid_dirs;
        username="$2"; 
        [ -z "$username" ] && { echo "no username specified"; exit 1; }; 
        find . -exec chown "$username:$username" {} +; shift 2;;
      -d|--dirperms)
        refuse_stupid_dirs;
        find . -type d -exec chmod 755 {} +; shift;;
      -f|--fileperms)
        refuse_stupid_dirs;
        find . -type f -exec chmod 644 {} +; shift;;
      -s|--scriptperms)
        refuse_stupid_dirs;
        find . -type f -exec chmod 755 {} +; shift;;
      -h|--help) 
        usage; exit 0;;
      --)
        shift ;;
      ""|*)
        break;;
    esac
  done
}
main "$@"
