#!/usr/bin/env bash
sed -Ei '/@lighttheme/ {s/^# //}; /@darktheme/ {s/^([^#])/# \1/}' \
    "$XDG_CONFIG_HOME/alacritty/alacritty.toml" \
    "$XDG_CONFIG_HOME/helix/config.toml"
lookandfeeltool --keep-auto --apply org.kde.breeze.desktop
pkill -USR1 hx
