#!/usr/bin/env bash
set -euo pipefail

checkcmd() {
	if ! command -v "$1" >/dev/null; then
		echo -e "Need the '$1' command, but it is not installed";
		exit 1;
	fi
}

sum() {
	awk '{ ms+=$1 } END { 
		s = ms / 1000;
		h = s / 3600;
		s = s % 3600;
		m = s / 60;
		s = s % 60;
		printf "%d:%.2d:%.2d\n", h, m, s;
	}'
}

# buggy, because it relies on DURATION: in metadata, which may not be there
# (in like 3 % of files I have)
get_ms_duration_ffmpeg() 
{
	checkcmd parallel
	checkcmd ffprobe
	parallel --null --eta 'ffprobe -hide_banner 2>&1' \
	| sed -n "/Video/,/DURATION/ p;" | grep DURATION | awk '{print $3;}' \
	| xargs -I {} -- date -d {} "+%s" \
 	| sed "s/$/*1000-$ms_start_of_day/" \
	| bc
}

get_ms_duration_exiftool() 
{
	checkcmd parallel
	checkcmd exiftool
	parallel --null --eta 'exiftool 2>&1' \
	| grep "^Duration" \
	| awk '{print $3}' \
	| xargs -I {} -- date -d {} "+%s" \
 	| sed "s/$/*1000-$ms_start_of_day/" \
	| bc
}

get_ms_duration_mediainfo()
{
	checkcmd parallel
	checkcmd mediainfo
	parallel --null --eta 'mediainfo --Inform="General;%Duration%"'
}

main() {
	[ -z "${1:-}" ] && { 
		echo -e "usage: $0 DIR\nCalculates total playtime of all media files in a dir.";
		exit 1;
	}
	ms_start_of_day="$(( $(date -d 00:00:00 +%s) * 1000))"


	# v~~ slow and broken
	# totaltime=$(find "${1:-}" -type f -print0 | get_ms_duration_ffmpeg | sum)
	# v~~ pretty fast, IO bound tho
	totaltime=$(find "${1:-}" -type f -print0 | get_ms_duration_mediainfo | sum)
	# v~~ very slow
	# totaltime=$(find "${1:-}" -type f -print0 | get_ms_duration_exiftool | sum)

	echo "$totaltime" | tee last-calculated-totaltime
}

main "$@"
