#!/usr/bin/env bash
#shellcheck disable=2059 # printf +variable
set -euo pipefail

# DON'T USE THIS
# 'mutool merge' works just fine with the bookmarks in there
# idk why i made this
# 
# merges files like pdfunite / mutool merge, but creates chapters from separate file names.
# From https://unix.stackexchange.com/questions/368415/merge-pdf-files-and-automatically-create-a-table-of-contents-with-each-file-as-a

# sadly the merging is broken if the pdfs have different page sizes, no matter what backend you use :(

out_file="combined.pdf"
tmp_out_file="out.pdf"
bookmarks_file="bookmarks.txt"
bookmarks_fmt="BookmarkBegin
BookmarkTitle: %s
BookmarkLevel: 1
BookmarkPageNumber: %d
"

i_have() { command -v "$1" >/dev/null; } 

dump_bookmarks_of_file() {
    file="$1"
    pages_so_far="$2"
    pdftk "$file" dump_data | grep Bookmark | (while read -r a b; do
        case "$a" in
            'BookmarkLevel:') 
                echo "BookmarkLevel: $((b + 1))";;
            'BookmarkPageNumber:') 
                echo "BookmarkPageNumber: $((b + pages_so_far))";;
            *) echo "$a $b";;
        esac
    done)
}

number_of_pages_in_file() {
    if i_have mutool; then
        # mutool pages "$1" | grep pagenum | wc -l
        mutool info "$1" | grep Pages | awk '{print $2}'
    else
        pdftk "$1" dump_data | grep NumberOfPages | awk '{print $2}'
    fi
}

usage() {
    echo "usage: $0 [--nest] file.pdf..."
    echo "merges the files, chapter/index aware"
    echo "--chapters      include chapters from each file (default)"
    echo "--no-chapters   don't"
    echo "--names         group by file name (default)"
    echo "--no-names      don't"
}

longopts="chapters,no-chapters,names,no-names"

main() {
    chapters=1
    names=1


    # parsed=$(getopt --longoptions="$longopts" --name "$0" -- "$@")
    # eval set -- "$parsed"
    # echo "$parsed"

    while true; do
        case "$1" in
            --chapters)    chapters=1; shift;;
            --no-chapters) chapters=0; shift;;
            --names)       names=1; shift;;
            --no-names)    names=0; shift;;
            --)            shift; break;;
            "")            usage; exit 0;;
            *)             break;;
        esac
    done

    if ! i_have pdftk; then
        echo "pdftk is required to extract chapters (also mutool from mupdf-tools is optional to get page counts faster)" >&2
        exit 1
    fi

    declare -a files=("$@")
    page_counter=1

    # Generate bookmarks file.
    for f in "${files[@]}"; do
        title="${f%.*}"

        if [ "$names" = "1" ]; then
            printf "$bookmarks_fmt" "$title" "$page_counter" >> "$bookmarks_file"
        fi
        if [ "$chapters" = "1" ]; then
            dump_bookmarks_of_file "$f" "$page_counter" >> "$bookmarks_file"
        fi
        num_pages="$(number_of_pages_in_file "$f")"
        page_counter=$((page_counter + num_pages))
        echo $page_counter
    done

    # Combine PDFs and embed the generated bookmarks file.
    # pdftk "${files[@]}" cat output - | \
    #    pdftk - update_info "$bookmarks_file" output "$out_file"

    ### all three create a garbled pdf if the pdfs differ in canvas size :(
    if i_have mutool; then
        mutool merge -o "$tmp_out_file" "${files[@]}"
    elif i_have pdfunite; then
        pdfunite "${files[@]}" "$tmp_out_file"
    else
        pdftk "${files[@]}" output "$tmp_out_file" # slowest
    fi

    if [ "$chapters" = 1 -o "$names" = 1 ]; then
        pdftk "$tmp_out_file" update_info "$bookmarks_file" output "$out_file"
    else
        mv "$tmp_out_file" "$out_file"
    fi

    # clean up after yourself
    rm -f "$tmp_out_file" "$bookmarks_file"
}

main "$@"
