#!/bin/sh

[ "$(whoami)" = root ] || { echo "Need to run kmscon as root. Otherwise, it completely freezes with no ability to Ctrl+C or Alt+Fx at all."; exit 1; }

# Allows to do some work under a Linux console (no X server, 1980s style).
# it is WAY better than fbcon, which has completely broken color parsing

# ----- Compatibility -----
# + brain (nearly zero distractions)
# > windowing (tabs, splits)
#   + use tmux or byobu (byobu has broken ctrl+b " fsr)
# > Other programs
#   > Console-based
#     + ok, need to force truecolor in Helix
#   > DRM-based
#     + mpv: works
#     + fbpdf: normal - black screen, fbterm - barely one page, kmscon - barely one page
#     + jfbview: normal - nothing, fbterm - works, kmscon - one stripe and segfaults when you scroll
#     - fbv: junk, just use mpv for images
#     - sometimes, auto VT switching doesn't work, you have to switch to different tty and back 
#   > X11-based
#     > use xinit (very limited, see the `poormans` script)
#     - can't resize
#     - running as root -> no settings
#     - ...
# - can't have bg pics :/
#   > the MacSlow version has some hardcoded shaders for --render-engine gltex
#      - had to change something in source to make it work, don't remember

# ---- Related tools -----
# - fgconsole(1):   number of current console term (prints 4 when on tty4)
# - showkey(1):     keycodes 
# - keymaps(5):     ???
# - anything in `yay -Ss framebuffer`
# - https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration


# ---- Unused settings / notes ----

       #--grab-zoom-in "" \
       #--grab-zoom-out "" \

       #--session-control on \  <-- broken idk
       #--xkb-keymap /home/karel/scripts/cz.mod4-is-superl.map \      <-- this wasn't necessary


kmscon \
       --verbose \
       --xkb-model pc105 \
       --xkb-layout cz \
       --xkb-variant qwerty \
       --xkb-options caps:swapescape,compose:ins \
       --xkb-repeat-rate 16 \
       --sb-size 70000 \
       --font-name "JetBrains Mono Bold" \
       --font-dpi 120 \
       --palette custom \
       --palette-foreground 0,0,0 \
       --palette-background 246,251,214 \
       --palette-light-green  0,140,0 \
       --palette-light-yellow 140,140,0 \
       --palette-light-cyan   0,128,128 \
       --palette-light-blue   0,64,128 \
       --hwaccel \
       --login -- /usr/bin/env bash -i

# these don't fix/do anything visible for me
# --no-drm \  
# --hwaccel \
# --render-engine bblit \
