#!/bin/sh

bookmark="$(xclip -o)"
file="$HOME/bookmarks"

if grep -q "^$bookmark$" "$file"; then
    notify-send "bm-add" "Bookmark already exists"
else
    echo "$bookmark" >> "$file"
    notify-send "bm-add" "Bookmark added"
fi

