#!/bin/sh

bookmark="$(xclip -o)"
file="$HOME/notes/bookmarks"

if grep -q "^$bookmark$" "$file"; then
    notify-send "$0" "Bookmark $bookmark already exists"
else
    echo "$bookmark" >> "$file"
    notify-send "$0" "Bookmark $bookmark added"
fi

