#!/bin/bash

# temp files
tf=/tmp/dashboard
notes=$HOME/notes
plainnotes="$notes/Plain"
ptd=$plainnotes/priv-todostack.md
td=$HOME/muni/bp/thesis/bpwork-todostack.md

mkdir -p $tf


cut_md_section()
{
	# file="$1"
	# the uniq is a hack to ignore multiple whitespace
	section="$1"
	sed -ne "/^# $section/,/^#/p;" | sed -e "1 d; $ d;" | cat -s

}

list_recent_files_in()
{
	ls -tcF "$1" | grep -v "[/@*]$" | head
}

box_with_title()
{
	boxes -d boxquote | sed -e "1s/.*/,----[ $1 ]/"
}

# prostě multibyte znaky jsou průser a nefungují vůbec
# musel bych si udělat vlastní  pr  defakto
pad_to_ideal_width()
{
	width=$(wc -L "$1" | cut -d" " -f1)
	# echo "ššš"
	# echo "$1"
	cat "$1" | (IFS="\n"; while read r; do
		printf "%s%*s\n" "$r" "$[$width - $(wc -L <<< "$r")]" "";
	done)

# 	for i in "${a[@]}" "${b[@]}"
# do printf "%s%*s|\n" "$i" "$[15 - $(wc -L <<< "$i")]" ""
# done

}
put_next_to_each_other()
{
	# the expand in pr doesn't work and I don't know why

	# wish it was aligned on the longest line but
	# i can't find a way to do it
	# and I don't know how to split streams and magically
	# reassemble the results

	# IFS="\n";
	# cat "$1" | (while read i; do
	# 	wc -L <<<"$i";
	# done)
	pad_to_ideal_width "$1" >$tf/1al
	pad_to_ideal_width "$2" >$tf/2al
	sanepr "$tf/1al" "$tf/2al" | expand
}

recreate()
{
	cat $ptd | cut_md_section Todo    | box_with_title "Ostatní práce" >$tf/todo
	cat $ptd | cut_md_section Doing   | box_with_title "Elementární kroky" >$tf/doing

	cat $td | cut_md_section "Break down further" | box_with_title "Bakalářka: práce na zpracování" >$tf/breakdown
	cat $td | cut_md_section "To do" | box_with_title "Elementární kroky" >$tf/bpsteps
	
	# list_recent_files_in $notes/Plain | box_with_title "Recent notes" >$tf/recentnotes

	cat $tf/breakdown $tf/bpsteps >$tf/col1
	cat $tf/todo $tf/doing >$tf/col2
	put_next_to_each_other $tf/col1 $tf/col2 >$tf/result

	# used to have  -size 1600x900 xc:black   for a blank pic
	convert $HOME/pic/nature_darkblur_small.jpg \
		-font "JetBrains-Mono-Light" -pointsize 22 -fill white \
		-gravity center \
		-annotate +30+30 "@$tf/result" $tf/result.jpg

	xwallpaper --center $tf/result.jpg
}


while true; do
	recreate
	inotifywait -t 60 -e "close_write" $plainnotes $td && recreate;
done
