#!/bin/bash

# temp files
tf=/tmp/dashboard
notes=$HOME/notes
plainnotes="$notes/Plain"
ptd=$plainnotes/priv-todostack.md
td=$HOME/muni/bp/thesis/bpwork-todostack.md

mkdir -p $tf


cut_md_section()
{
	# section="$1"
	sed -ne "/^# $1/,/^#/p;" | sed -e "1 d; $ d;" | cat -s
}

box_with_title()
{
	boxes -d boxquote | sed -e "1s/.*/,----[ $1 ]/"
}

cut_and_embox()
{
	# [ -z "$2" ] && set "$1" "$1"
	cut_md_section "$1" | box_with_title "${2:-$1}"
}

list_recent_files_in()
{
	ls -tcF "$1" | grep -v "[/@*]$" | head
}

# pad_to_ideal_width()
# {
# 	width=$(wc -L "$1" | cut -d" " -f1)
# 	cat "$1" | (IFS="\n"; while read r; do
# 		printf "%s%*s\n" "$r" "$[$width - $(wc -L <<< "$r")]" "";
# 	done)
# }

put_next_to_each_other()
{
	cat "$1" >$tf/1al
	cat "$2" >$tf/2al

	# pr which actually works with UTF-8 characters
	# see the C source, don't think there's a coreutil
	# it's definitely nontrivial to do with bash programs
	sanepr "$tf/1al" "$tf/2al"
}

recreate()
{
	# cat $ptd | tee >(cut_and_embox "Todo") >/dev/null | cat >$tf/col1

	cat $ptd | tee \
		>(cut_and_embox "Todo") \
		>(cut_and_embox "Další poznámky") \
		>(cut_and_embox "Doing") \
		>(cut_and_embox "Zkoušky") \
		>/dev/null | cat >$tf/col1

	cat $td | tee \
		>(cut_and_embox "Break down further" "Bakalářka: práce na zpracování") \
		>(cut_and_embox "To do" "Elementární kroky") \
		>(cut_and_embox "Zkoušky") \
		>/dev/null | cat >$tf/col2
		
	put_next_to_each_other $tf/col1 $tf/col2 >$tf/result

	# used to have  -size 1600x900 xc:black   for a blank pic
	convert "$WALLPAPER" \
		-fill black -colorize 50% \
		-font "JetBrains-Mono-Light" -pointsize 18 -fill white \
		-gravity center \
		-annotate +30+30 "@$tf/result" $tf/result.jpg

	xwallpaper --center $tf/result.jpg
}


while true; do
	recreate
	inotifywait -e "close_write" $plainnotes $td && recreate;
done
