#!/bin/sh

selector() {
    if [ -z "$can_notify" ]; then
        assert ihave fzf
        fzf
    else
        assert ihave dmenu
        dmenu -p "$1"
    fi
}

f_mnt() 
{
    echo asdjfl
    drive="$1"
    [ -z "$drive" ] && {
        drivebase=$(echo "$files" | selector "Which device to mount?")
        [ -z "$drivebase" ] && exit 1
        drive="/dev/disk/by-label/$drivebase"
    }
    $notifysend udisksctl "$(udisksctl mount -b "$drive" 2>&1)"
}

f_umount()
{
    drive="$1"

    [ -z "$drive" ] && {
        drivebase=$(echo "$files" | selector "Which device to unmount?")
        [ -z "$drivebase" ] && exit 1
        drive="/dev/disk/by-label/$drivebase"
    }
    $notifysend udisksctl "$(udisksctl unmount -b "$drive" 2>&1)"

    [ -n "$poweroff" ] && {
        poweroff_info="$(udisksctl power-off -b "$drive" 2>&1)"
        [ -z "$poweroff_info" ] && {
            poweroff_info="Drive $drive is now powered off."
        }
        $notifysend udisksctl "$poweroff_info"
    }
}

ihave() {
    command -v "$1" >/dev/null
}

assert() {
    cmd="$1"
    shift
    "$cmd" "$@" || { $notifysend "$prog" "assertion '$cmd $@' failed"; exit 1; }
}

usage() {
    echo "usage: $0 --notify|-p|--poweroff|-h|--help"
    echo "-n|--notify     use notify-send instead of echo"
    echo "-p|--poweroff   unmount will also poweroff"
    echo "-h|--help       this help"
}

notifications_work() {
    timeout 0.2 notify-send -t 1 $0 "testing if notifications are consumed. If you are reading this, your DE/WM ignores the notification timeout, because it should be gone after a millisecond. Suggest how to do this better."  # non-zero on timeout
}

main() {    
    IFS=" "
    notifysend="echo"
    prog="$(basename "$0")"
    poweroff=""

    assert ihave udisksctl

    for arg in "$@"; do
        case "$arg" in
            -n|--notify) assert notifications_work; can_notify=1; notifysend="notify-send -t 4000"; shift;;
            -p|--poweroff) poweroff=1; shift;;
            -h|--help) usage; exit 0;;
            -*) usage; exit 1;;
            *) ;;
        esac
    done

    files=$(ls /dev/disk/by-label | sed -e '/^NO_LABEL$/d' | sed -e '/^swap$/d')

    case "$(basename "$0")" in
        amount) f_mnt "$@";;
        aumount) f_umount "$@";;
        *) notify-send -u critical "diskshit" "bad symlink, got $0"; exit 1;;
    esac

}

main "$@"
