#!/usr/bin/env bash


choices=( suspend hibernate poweroff reboot logout )
choice="$(IFS=$'\n'; dmenu-provider -p "See you next time." <<< "${choices[*]}")"

case "$choice" in
    suspend|hibernate|poweroff|reboot) systemctl "$choice";;
    logout) bspwm quit; i3-msg exit;;
esac
