#!/bin/bash
set -euo pipefail
#shellcheck disable=SC2068

if [ -t 1 ]; then
	if command -v fzf >/dev/null; then
		fzf "$@";
	fi
elif command -v rofi >/dev/null; then
	rofi -dmenu "$@";
elif command -v dmenu >/dev/null; then
	dmenu "$@";
else
	notify-send "$0" "I was asked to display a menu, but cannot! Install rofi or dmenu.\n"
fi
