#!/bin/bash

options="suspend
hibernate
poweroff
reboot
logout"

choice="$(rofi -dmenu -p "See you next time." <<< "$options")"

case "$choice" in
    suspend|hibernate|poweroff|reboot) systemctl "$choice";;
    logout) bspwm quit; i3-msg exit;;
esac
