#!/bin/bash
set -euo pipefail

# reloads crashed Atheros wifi module

[ "$EUID" != 0 ] && {
  echo "Reloading kernel modules requires root"; exit 1;
}

ls /lib/modules | grep -q "$(uname -r)" || {
  echo "(!) Kernel was updated but the system was not restarted yet."
  echo "There are no kernel modules for the currently running kernel,"
  echo "so unloading one would mean I can't reload it again."
  echo "This would make wifi unusable until reboot."
  exit 1
}

sudo rmmod ath10k_pci
sudo modprobe ath10k_pci
