#!/bin/sh
inotifywait -e "close_write" /etc/hosts && { 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  wall "Don't change /etc/hosts, you stupid shit"; 
  shutdown 0;
} 
