#!/usr/bin/env bash
set -euo pipefail


[ "$EUID" -ne 0 ] && { echo "Pacman must be run this as root"; exit 1; }

#################################################
# some of this could see some cleanup
################################################

# autocomplete / checks for various langs for Helix (or other editors)
lsp=(
	texlab
	python-lsp-server
	svelte-language-server
	haskell-language-server
	bash-language-server
	lua-language-server          # nvim
	vscode-html-languageserver
	vscode-css-languageserver
	vscode-json-languageserver
)
python_modules=(
	python-pyserial  # hw dev
)

web_browsers=(
	firefox  firefox-tridactyl  firefox-ublock-origin 
	chromium 
	qutebrowser
)

# todo: cleanup / split
guiutils=(
	xdotool xclip xcolor
	wl-clipboard
	network-manager-applet dmenu rofi rpi-imager xdot timeshift uget meld sqlitebrowser
	debugedit picom libspeechd speech-dispatcher numlockx dunst xf86-video-intel unclutter redshift dex
	wine winetricks
	# bluetooth?
	qt5-connectivity qt6-connectivity
	syncthing
	tectonic
	# plasma wants this
	power-profiles-daemon
	# xev, xkill and more
	xorg-apps

	# virtualization
	virt-manager
	qemu-desktop
)

cliutils=(
	wget curl aria2 fd fzf kexec-tools brightnessctl cpupower zip p7zip pass parallel ccache less man
	# bluetooth
	bluez-utils 
	linux-wifi-hotspot haveged dnsmasq
	translate-shell
	powertop
	# mkfs.fat
	dosfstools
	man-pages
)

programming=(
	vim helix  # editing
	git imagemagick  alacritty htop bcc-tools  tmux byobu intel-gpu-tools  # misc tools
	tcc valgrind clang bear # c
	rust # rust
	jdk21-openjdk # java
	shellcheck  # bash
	protobuf # interop
	verilator # hw dev
)

rice=(
	polybar i3 sxhkd bspwm
)

media=(
	yt-dlp pamixer sxiv mpv xwallpaper lf ueberzug zathura zathura-ps zathura-djvu zathura-pdf-mupdf maim
)

fonts=(
	ttf-jetbrains-mono ttf-jetbrains-mono-nerd noto-fonts-cjk
)

texlive_all=(
	# use tectonic instead if possible
	texlive texlive-lang 
)


guionly=(
	"${web_browsers[@]}" 
	"${media[@]}" 
	"${rice[@]}" 
	"${fonts[@]}" 
	"${wine[@]}"
	"${guiutils[@]}"
)
clionly=(
	"${programming[@]}" 
	"${lsp[@]}" 
	"${cliutils[@]}"
	"${python_modules[@]}"
)

case "${1:-}" in
    cli) everything=("${clionly[@]}");;
    gui) everything=("${clionly[@]}" "${guionly[@]}");;
    guitex) everything=( "${guionly[@]}" "${clionly[@]}" "${texlive_all[@]}" );;
    *) echo "usage: $0 cli/gui/guitex"; exit 1;;
esac

pacman -Syu --noconfirm --needed "${everything[@]}"
# pacman -Fy  -- like 50M, shouldn't be updated every 5 minutes

