#!/bin/bash
alsoprint() {
    echo "$@" && "$@"
}

set -euo pipefail

[ "$EUID" -eq 0 ] && { echo "yay musst be run as regular user"; exit 1; }
cd "$HOME"

# Get yay
if ! pacman -Qq yay >/dev/null; then
    pushd /tmp; {
        git clone https://aur.archlinux.org/yay.git || true
        cd yay
        makepkg -si
    }; popd
fi

ug=(
    libnatpmp opencv libcaca libjuice sdl_ttf
)
lsp=(
    vim-language-server cmake-language-server prisma-language-server awk-language-server
)
browsers=(
)
sw_management=(
    powerpill downgrade
)
programming=(
    emsdk uefi-run vscodium-bin sysls jdk21-openjdk bear perf-tools flamegraph
)
rice=(
    i3-swallow-git 
)
games=(
    python-wpm 
)
editing=(
    vimv-git 
)
media=(
    yt-dlp-drop-in
)
utils=(
    tatsumato hotspot kddockwidgets kddockwidgets-qt6 task-spooler update-grub boxes ananicy
)
# Install AUR programs
yay -S --noconfirm --needed \
    "${browsers[@]}"      \
    "${editing[@]}"       \
    "${games[@]}"         \
    "${media[@]}"         \
    "${programming[@]}"   \
    "${rice[@]}"          \
    "${sw_management[@]}" \
    "${utils[@]}"         \
    "${lsp[@]}"           \
    "${ug[@]}"            \
  

# Post install startups
alsoprint systemctl enable --now ananicy

# My own configs
{
    git clone git@gitlab.com:nochar/bash_scripts.git scripts 2>/dev/null || true
    git clone git@gitlab.com:nochar/dotfiles.git .config 2>/dev/null || true
    pushd .config/zroot
    ./make_symlinks -f
    popd
}


