#!/bin/bash
set -euo pipefail

[ "$EUID" -ne 0 ] && { echo "Pacman must be run this as root"; exit 1; }

# was using the git version of zathura but forgot why

lsp=(
    texlab python-lsp-server svelte-language-server haskell-language-server bash-language-server
)
browsers=(
    firefox chromium qutebrowser
)
# should these two even be separate?
plumbing=(
    debugedit picom libspeechd speech-dispatcher network-manager-applet numlockx dunst 
)
utils=(
    wget curl aria2 fd fzf  unclutter kexec-tools dmenu xdotool xclip brightnessctl cpupower zip p7zip redshift 
)
programming=(
    git imagemagick alacritty htop shellcheck intel-gpu-tools jdk21-openjdk
)
rice=(
    polybar tmux byobu i3 sxhkd bspwm
)
editing=(
    vim helix texlive texlive-lang zathura zathura-ps zathura-djvu zathura-pdf-mupdf
)
media=(
    yt-dlp pamixer sxiv mpv xwallpaper maim
)
fonts=(
    ttf-jetbrains-mono ttf-jetbrains-mono-nerd
)

pacman -Syu --noconfirm --needed
pacman -S --noconfirm --needed     \
    "${browsers[@]}"      \
    "${editing[@]}"       \
    "${media[@]}"         \
    "${plumbing[@]}"   \
    "${utils[@]}"   \
    "${programming[@]}"   \
    "${rice[@]}"          \
    "${fonts[@]}"         \
    "${lsp[@]}"         \


