#!/usr/bin/env bash

# XXX: this is ugly, also use chaotic-aur versions where possible

alsoprint() {
    echo "$@" && "$@"
}

set -euo pipefail

[ "$EUID" -eq 0 ] && { echo "yay musst be run as regular user"; exit 1; }
cd "$HOME"

# Get yay
if ! pacman -Qq yay >/dev/null; then
    pushd /tmp; {
        git clone https://aur.archlinux.org/yay.git || true
        cd yay
        makepkg -si
    }; popd
fi

# required!
progs=(
    systemd-boot-pacman-hook
    pacman-hook-kernel-install
)

# old=( 
#     # -- libs
#     libbacktrace-git   # XXX: ???
#     # -- lsp
#     vim-language-server cmake-language-server awk-language-server 
#     # --sw management
#     powerpill downgrade 
#     # --programming
#     emsdk uefi-run vscodium-bin sysls jdk21-openjdk bear flamegraph git-lfs 
#     # --i3
#     i3-swallow-git 
#     # -- games
#     python-wpm 
#     # -- media
#     yt-dlp-drop-in 
#     # -- utils
#     tatsumato hotspot kddockwidgets-qt6 task-spooler update-grub boxes translate-shell xdg-ninja vimv-git 
# )

# Install AUR programs
yay -S --noconfirm --needed "${progs[@]}"

# Post install startups
# alsoprint systemctl enable --now ananicy 

# My own configs (XXX: this belongs elsewhere !!!!!)
postinstall()
{
    git clone git@gitlab.com:nochar/bash_scripts.git "$HOME"/scripts  2>/dev/null || true
    git clone git@gitlab.com:nochar/dotfiles.git     "$HOME"/dotfiles 2>/dev/null || true
    pushd dotfiles; {
        stow home
        sudo stow root --target=/
    }; popd
}


