#!/usr/bin/env bash
set -euo pipefail

# XXX: this is ugly and has junk that should be elsewhere
# also I should try to setup and use chaotic-aur


aur_install() {
    if command -v pamac; then
        pamac build "$@"
    elif command -v yay; then
        yay -S --noconfirm --needed "$@"
    elif command -v paru; then
        yay -S --noconfirm --needed "$@"
    else
        echo "E: no known AUR helper installed (tried pamac/yay/paru)"
        exit 1
    fi
}
aur_install "${progs[@]}"


# required!
progs=(
    systemd-boot-pacman-hook
    pacman-hook-kernel-install
    anki-bin
)

[ "$EUID" -eq 0 ] && { 
    echo "yay must be run as regular user"; 
    exit 1; 
}


# Get yay ?
# cd "$HOME"
# if ! pacman -Qq yay >/dev/null; then
#     pushd /tmp; {
#         git clone https://aur.archlinux.org/yay.git || true
#         cd yay
#         makepkg -si
#     }; popd
# fi


# old=( 
#     # -- libs
#     libbacktrace-git   # XXX: ???
#     # -- lsp
#     vim-language-server cmake-language-server awk-language-server 
#     # --sw management
#     powerpill downgrade 
#     # --programming
#     emsdk uefi-run vscodium-bin sysls jdk21-openjdk bear flamegraph git-lfs 
#     # --i3
#     i3-swallow-git 
#     # -- games
#     python-wpm 
#     # -- media
#     yt-dlp-drop-in 
#     # -- utils
#     tatsumato hotspot kddockwidgets-qt6 task-spooler update-grub boxes translate-shell xdg-ninja vimv-git 
# )
