#!/bin/sh
# intentional typo in name
#    nonroot kmscon<TAB><Enter> still runs kmscon and breaks your VT.

# Allows to do some work under a Linux console (no X server, 1980s style).

# Why? / What does it feel like?
# - no distractions whatsoever
# - byobu <3
#   - sadly, ctrl-X  and shift-X sometimes don't work => no splits, apps limited
# - inside kmscon, mpv works
#   - can view videos, music, images
#   - fbpdf/jfbview used to work but is now completely broken for me
# - outside of the kmscon:
#   - other apps work with xinit, poorly
#     - can't resize, running as root -> no settings, ...
#     - see my 'poormans' wrapper

# Is it usable for serious usage?
# - No.

# Related tools?
# - fgconsole         number of current console term (prints 4 when on tty4)
# - search pacman/aur for "framebuffer", I guess. Good luck.

[ "$(whoami)" = root ] || { echo "Need to run kmscon as root"; exit 1; }

# 17 is in ms
kmscon --xkb-layout cz \
       --xkb-variant qwerty \
       --xkb-repeat-rate 17 \
       --xkb-options caps:swapescape \
       --sb-size 70000 \
       --font-name "JetBrains Mono Bold" \
       --font-dpi 120 \
       --grab-zoom-in "" \
       --grab-zoom-out "" \
       --login -- /bin/bash -i

       # these don't fix anything
       # --no-drm \  
       # --hwaccel \
       # --render-engine bblit \
