#!/bin/bash

lsipath=/etc/systemd/logind.conf.d/lidswitch-inhibit.conf

# TODO: assumes graphical session, idk how to check for it for now
# TODO: this is a really hacky implementation, need to create that .conf inhibit somehow

# sudo_helper='kdesu -c'
sudo_helper='gksu'
# sudo_helper='sudo sh -c '

doitforreal()
{
	case "$1" in
		sleep|s)    $sudo_helper "mv ${lsipath} ${lsipath}.inactive || true; systemctl reload systemd-logind"; exit 0;;
		nosleep|ns) $sudo_helper "mv ${lsipath}.inactive ${lsipath} || true; systemctl reload systemd-logind"; exit 0;;
	esac
}
case "$1" in
	sleep|s|nosleep|ns) doitforreal "$1";;
	help|h|"") echo "usage: $0 sleep/nosleep";
			echo "disables or enables a lid-switch suspend inhibit in a hacky way (moving some config file)";;
	*) set "$(dmenu -p "which one?" <<<"sleep
nosleep" )"; doitforreal "$1";;
esac
