#!/bin/bash
# I don't know how to do this without polling
# inotifywait doesn't work on /sys
# udevadm monitor doesn't report perc change
# don't care anymore, this is very low prio just not to inflate PIDs but I don't know
# how to make this better atm

bat="/sys/class/power_supply/BAT0"

get_battery_perc() {
	cat "$bat/capacity"
}

is_battery_discharging() {
	grep -q "Discharging" "$bat/status"
}

upper_limit=15
lower_limit=7
mark=upper

while true; do 
	perc=$(get_battery_perc) 

	if is_battery_discharging; then 

		case $mark in
		upper) 
			if [[ $perc -le $upper_limit ]]; then
				notify-send "Battery is low" "Currently at $perc %"
				mark=lower
			fi;;
		lower) 
			if [[ $perc -le $lower_limit ]]; then
				notify-send -u critical "Critical battery level" "Currently at $perc %"
				mark=none
			fi;;
		esac

	else
		mark=upper
	fi 

	sleep 3
done

