#!/bin/sh
# pink -- A manual Redshift-based color control.

# date +"%s.%N"  -- for benchmarking, takes about 50 ms rn which is very slow but whatever

usage() {
    echo "usage: $0 -c TEMP|up|down"
    echo "brightness   from 1 to 100"
    echo "TEMP    color temperature from 1000 to 25000 K"
    echo "down    multiplies current temp by 1.1, capping at 6500 K (white)"
    echo "up      divides current temp by 1.1, capping at 1000 K (red)"
    echo ""
    echo "usage: $0 -b VALUE|up|down"
    echo "VALUE   software brightness from 1 to 100"
    echo "down    subtracts 5"
    echo "up      adds 5"
}

isdigit() {
    [ "$1" -eq "$1" ]
}

min() {
    echo $(( $1 < $2 ? $1 : $2 ))
}

max() {
    echo $(( $1 > $2 ? $1 : $2 ))
}

is_running_under_X() {
    # TODO: check if X server is running
    # not using X11/wayland is kinda dumb so idc for now
    true;
    # false;
}

color() 
{
    temp_change=1.03   # multiplicative
    bri_change=0.05    # additive
    max_temp=6500
    min_temp=1000
    current_temp=$(cat /tmp/red-colortemp)
    current_bri=$(cat /tmp/red-colorbri)

    cmd="$1"
    shift

    # failsafes: when running this script 20+ times a second (holding a key),
    # sometimes the file would be cleared without any value being set.
    # This fixes it hopefully
    [ -z "$current_temp" ] && current_temp=6500
    [ -z "$current_bri" ] && current_bri="1.0"

    desired_temp="$current_temp"
    desired_bri="$current_bri"

    if [ "$cmd" = "-b" ]; then
        if [ "$1" = "up" ]; then
            desired_bri=$(python -c "print(max(min(1.0, $current_bri+$bri_change), 0.1))") \
                || { echo "bad number"; exit 1; }
        elif [ "$1" = "down" ]; then
            desired_bri=$(python -c "print(max(min(1.0, $current_bri-$bri_change), 0.1))") \
                || { echo "bad number"; exit 1; }
        # TODO: missing case for immediate value (check if it's float)
        else
            echo "Argument is not a number" >&2; exit 1; 
        fi
    elif [ "$cmd" = "-c" ]; then
        if [ "$1" = "up" ]; then
            desired_temp=$(min "$max_temp" "$(echo "($current_temp * $temp_change) / 1" | bc)")
        elif [ "$1" = "down" ]; then
            desired_temp=$(max "$min_temp" "$(echo "$current_temp / $temp_change" | bc)")
        elif isdigit "$1"; then
            desired_temp=$1
        else
            echo "Argument is not a number" >&2; exit 1; 
        fi
    fi

    echo "$desired_temp" > "/tmp/red-colortemp"
    echo "$desired_bri" > "/tmp/red-colorbri"

    # bypass the long restore animation. 
    # Unconditional, pgrep is really slow btw
    killall -KILL redshift 2>/dev/null

    method="drm"

    is_running_under_X && {
        lastid="$(cat /tmp/last-notification)"
        [ -n "$lastid" ] && lastid_arg="-r $lastid" || lastid_arg=""
        # shellcheck disable=SC2086
        newid="$(notify-send $lastid_arg -p -t 700 "$(basename "$0")" "Setting screen color temp to ${desired_temp}K")"
        echo "$newid" > /tmp/last-notification
        method="randr"
    }
    echo "$desired_bri"
    redshift -P -b ${desired_bri}:1.0 -m "$method" -O "$desired_temp" >/dev/null
}



[ "$#" != 2 ] && { usage; exit 0; }
color "$@"
