#!/usr/bin/env bash

usage() {
    echo "usage: $0 (COLOR|-r)"
    echo "creates a single color bg with that color (try: teal, sea green, #400f3d)"
    echo "for options, see https://en.wikipedia.org/wiki/X11_color_names"
    echo "-r picks a random color (max 50 % brightness)"
}

rndcol() {
    echo $((RANDOM % 128))
}

case "$1" in
    "") usage; exit 1;;
    "-r") 
        color="$(printf "#%.2x%.2x%.2x" "$(rndcol)" "$(rndcol)" "$(rndcol)")";
        echo "$color";;
    "-*") usage; exit 1;; # doesn't get matched, idk how the matching works
    *) color="$1";;
esac

pixdir="$(xdg-user-dir PICTURES)"
[ ! -d "$pixdir" ] && { 
    echo "E: I'd like to place the wallpaper into your pictures directory (xdg-user-dir PICTURES, \"$pixdir\")"
    echo "E: it is not a dir. Please fix it in ~/.config/user-dirs.dirs and then run xdg-user-dirs-update."
    exit 1;
}

# convert -size 100x100 xc:"$color" ~/.config/wal.png
magick -size 1920x1080 xc:"$color" "$pixdir/wallpaper.png"
mv "$pixdir/wallpaper.png" "$pixdir/wallpaper"
xwallpaper --zoom "$pixdir/wallpaper"
