#!/bin/sh

NOTE=$(basename "$0")

fusage()
{
    echo "$NOTE - Skript pro zaznamenávání a správu poznámek."
    echo "Použití: $NOTE [verb [object]]"
    echo "         note object"
    echo ""
    echo "$NOTE [h[elp]]             Vypíše tuto nápovědu."
    echo "$NOTE l[ist]               Vypíše seznam poznámek."
    echo "$NOTE s[how] name          Vypíše poznámku."
    echo "$NOTE e[dit] name          Otevře poznámku ve Vimu, případně vytvoří novou."
    echo "$NOTE r[ename] old new     Přejmenuje poznámku old na new."
    echo "$NOTE d[elete] name        Přesune poznámku do adresáře trash vedle poznámek"
    echo "$NOTE fd[elete] name       Smaže poznámku natrvalo"
    echo "$NOTE name                 Stejné jako note s[how] name (když name není list/show/...)"
}

flistdir()
{
    ls -- *.md
}

fspecified()
{
    [ -z "$1" ] && { echo "No note specified"; return 1; }
    return 0;
}

fexists()
{
    [ -f "$1" ] || { echo "$1 doesn't exist or is not a regular file"; return 1; }
    return 0;
}

frename()
{
    [ -f "$1" ] || return 1;
    [ "$2" = ".md" ] && { echo "New name not specified"; return 1; }
    [ -d "$2" ] && { echo "Target $2 is an existing directory; I want to rename, not move"; return 1; }
    mv "$1" "$2"
}

# shopt -s expand_aliases
basepath=$HOME/notes/Plain
notename="$2".md

cd "$basepath" || exit

case "$1" in
    help|h|"") fusage;;
    list|l) flistdir;;
    show|s) fspecified "$notename" && fexists "$notename" && cat "$notename";;
    edit|e) fspecified "$notename" && $EDITOR "$notename";;
    rename|r) frename "$notename" "$3".md;;
    delete|d) mkdir -p trash; mv "$notename" trash;;
    fdelete|fd) rm "$notename";;
    *) cat "$1".md
esac

