#!/bin/bash
PTH=/home/nick/Shrine/Dokumenty/Plaintext/Poznámky
NOTENAME="$1"

shopt -s expand_aliases

cd "$PTH"

[ -z $NOTENAME ] && { find * -maxdepth 0 -type f; } || vim "$PTH"/"$NOTENAME".md

cd - >/dev/null
