#!/bin/bash
# ^ don't ever run shell scripts interactively with -i, this destroys your history

# don't know why this works
args-to-lines() {
    for line in "$@"; do
        echo -en "$line\n"
    done
}

dmenu-with-opts() {
    IFS=" "
    prompt="How should I open this?"
    echo $(args-to-lines "$@") | dmenu -p "$prompt"
}

suitable-program-for() {
    filename="$1"
    mime=$(file -L -b --mime-type "$filename")
    case "$mime" in
        application/epub+zip) echo zathura;;
        application/json) dmenu-with-opts "jq ." vim kwrite;;
        application/pdf) echo zathura;;
        application/javascript) echo $EDITOR;;  # .lua is detected as this
        audio/*) echo command mpv;;
        document/*) echo zathura;;
        html/*) echo firefox;;
        image/vnd.djvu) echo zathura;;
        image/*) echo sxiv;;
        inode/directory) echo dolphin;;
        inode/x-empty) echo $EDITOR;;
        text/*) echo $EDITOR;;
        video/*) echo mpv;;
        application/vnd.ms-htmlhelp) echo kchmviewer;;
        *) echo xdg-open;;
    esac
}

can-swallow()
{
    # how do I check if i3 is running?
    # ??? && echo swallow || echo ""
    pgrep i3 >/dev/null && echo "swallow" || echo ""
}

cmd=""
file=""

whattorun() {
    echo "whattorun is run with these arguments:" >&2
    echo "$@" >&2

    # spawn in a new terminal if -t is given
    termprefix=""
    [ "$1" = "-t" ] && { termprefix="$TERMINAL -e "; shift; }
        
    # bandaid fix, should fix how this script is really called
    file="$*"
    program="$(suitable-program-for "$file")"

    echo "suitable-program-for returned $program for $file" >&2

    case "$program" in
        zathura|sxiv) 
            cmd="${termprefix} $(can-swallow) $program"
        ;;
        $EDITOR) 
            if [ -w "$file" ]; then 
                 cmd="$termprefix $EDITOR"
             else
                 echo "Not writable, trying sudoedit..." >&2;
                 cmd="$termprefix sudoedit"
             fi
        ;;
        "") echo "bug in suitable-program-for, should return xdg-open" >&2; exit 1;;
        *) cmd="$termprefix $program";;  # program is unquoted to allow for args
    esac
}

whattorun $@

echo cmd is $cmd
echo file is $file
$cmd "$file"

# haven't checked this and I don't really want this that much
echo "$cmd \"$file\"" >> $HOME/.local/state/bash/history
