#!/bin/bash

# don't know why this works
args-to-lines() {
    for line in "$@"; do
        echo -en "$line\n"
    done
}

dmenu-with-opts() {
    IFS=" "
    prompt="How should I open this?"
    echo $(args-to-lines "$@") | dmenu -p "$prompt"
}

suitable-program-for() {
    filename="$1"
    mime=$(file -L -b --mime-type "$filename")
    case "$mime" in
        application/epub+zip) echo zathura;;
        application/json) dmenu-with-opts "jq ." vim kwrite;;
        application/pdf) echo zathura;;
        audio/*) echo command mpv;;
        document/*) echo zathura;;
        html/*) echo firefox;;
        image/vnd.djvu) echo zathura;;
        image/*) echo sxiv;;
        inode/directory) echo dolphin;;
        inode/x-empty) echo $EDITOR;;
        text/*) echo $EDITOR;;
        video/*) echo mpv;;
        application/vnd.ms-htmlhelp) echo kchmviewer;;
        *) echo xdg-open;;
    esac
}

can-swallow()
{
    # how do I check if i3 is running?
    # ??? && echo swallow || echo ""
    [ "$WM" = i3 ] && echo "swallow" || echo ""
}

main() {

    # spawn in a new terminal if -t is given
    termprefix=""
    [ "$1" = "-t" ] && { termprefix="$TERMINAL -e "; shift; }
        
    file="$1"
    program="$(suitable-program-for "$file")"

    echo "suitable-program-for returned $program for $file"

    case "$program" in
        zathura|mpv|sxiv) $termprefix $(can-swallow) $program "$file";;
        $EDITOR) 
            if [ -w "$file" ]; then 
                 $termprefix $EDITOR "$file";
             else
                 echo "Not writable, trying sudoedit..."
                 $termprefix sudoedit "$file";
             fi;;
        "") echo "bug in suitable-program-for, should return xdg-open"; exit 1;;
        *) $termprefix $program "$file";;  # program is unquoted to allow for args
    esac
}

main "$@"
