#!/usr/bin/env bash
#shellcheck disable=2059 # printf +variable

# merges files like pdfunite / mutool merge, but creates chapters from separate file names.
# From https://unix.stackexchange.com/questions/368415/merge-pdf-files-and-automatically-create-a-table-of-contents-with-each-file-as-a

# sadly the merging is broken if the pdfs have different page sizes, no matter what backend you use :(

out_file="combined.pdf"
bookmarks_file="./bookmarks.txt"
bookmarks_fmt="BookmarkBegin
BookmarkTitle: %s
BookmarkLevel: 1
BookmarkPageNumber: %d
"

i_have() { command -v "$1" >/dev/null; } 

dump_bookmarks_of_file() {
    file="$1"
    pages_so_far="$2"
    pdftk "$file" dump_data | grep Bookmark | (while read -r a b; do
        case "$a" in
            'BookmarkLevel:') 
                echo "BookmarkLevel: $((b + 1))";;
            'BookmarkPageNumber:') 
                echo "BookmarkPageNumber: $((b + pages_so_far))";;
            *) echo "$a $b";;
        esac
    done)
}

number_of_pages_in_file() {
    if i_have mutool; then
        # mutool pages "$1" | grep pagenum | wc -l
        mutool info "$1" | grep Pages | awk '{print $2}'
    else
        pdftk "$1" dump_data | grep NumberOfPages | awk '{print $2}'
    fi
}

usage() {
    echo "usage: $0 [--nest] file.pdf..."
    echo "merges the files, chapter/index aware"
    echo "--no-nest  builds chapter index from file names (default)"
    echo "--nest     additionally captures chapters from each name under that filename"
    echo "           (slow, blame pdftk)"
}

main() {
    nest=0

    case "${1:-}" in
        --nest)    nest=1; shift;;
        --no-nest) nest=0; shift;;
        "")        usage; exit 0;;
        --*)       usage; exit 1;;
    esac

    if ! i_have pdftk; then
        echo "pdftk is required to extract chapters (also mutool is optional to get page counts faster)" >&2
        exit 1
    fi

    rm -f "$bookmarks_file" "$out_file"

    declare -a files=("$@")
    page_counter=1

    # Generate bookmarks file.
    for f in "${files[@]}"; do
        title="${f%.*}"

        if [ "$nest" = "1" ]; then
            printf "$bookmarks_fmt" "$title" "$page_counter" >> "$bookmarks_file"
            dump_bookmarks_of_file "$f" "$page_counter" >> "$bookmarks_file"
        else
            printf "$bookmarks_fmt" "$title" "$page_counter" >> "$bookmarks_file"
        fi
        num_pages="$(number_of_pages_in_file "$f")"
        page_counter=$((page_counter + num_pages))
        echo $page_counter
    done

    # Combine PDFs and embed the generated bookmarks file.
    # pdftk "${files[@]}" cat output - | \
    #    pdftk - update_info "$bookmarks_file" output "$out_file"

    ### all three create a garbled pdf if the pdfs differ in canvas size :(
    if i_have mutool; then
        mutool merge -o "out.pdf" "${files[@]}"
    elif i_have pdfunite; then
        pdfunite "${files[@]}" out.pdf
    else
        pdftk "${files[@]}" output out.pdf # slowest
    fi
    pdftk "out.pdf" update_info "$bookmarks_file" output "$out_file"
}

main "$@"
