#!/bin/sh

sudo_commands="hotspot"
geom_commands="hotspot mpv"

must_use_sudo_for()
{
    echo "$sudo_commands" | grep -q "$1"
}

must_use_geom_for()
{
    echo "$geom_commands" | grep -q "$1"
}

prog=$1
shift
must_use_sudo_for $prog && maybe_sudo="sudo"
must_use_geom_for $prog && maybe_geom="-geometry 1920x1080+0+0"

$maybe_sudo xinit /usr/bin/$prog $maybe_geom "$@" -- :0 vt3
