#!/bin/bash

fusage()
{
    echo "Skript  pwmask  vytváří uživatelsky určenou sekvenci souhlásek a samohlásek."
    echo ""
    echo "Použití:   pwmask MASK"
    echo ""
    echo "MASK je řetězec obsahující c a w: např. cwccwccwcwcwc"
    echo "Znak 'c' se nahradí za náhodnou souhlásku, 'w' za náhodnou samohlásku."
}

# Picks a random letter from $1.
pickfrom()
{
    echo "${1:$[$RANDOM % ${#1}]:1}"
}

wovels="aeiouy"
consonants="bcdfghjklmnpqrstvwxz"
mask="$1"
result=""

[ $mask == "-h" -o $mask == "--help" ] && { fusage; exit 0; }

for (( i=0; i<${#mask}; i++)); do
    byte="${mask:$i:1}"
    case $byte in
        c) result="$result$(pickfrom "$consonants")";;
        w) result="$result$(pickfrom "$wovels")";;
        *) echo "Invalid letter, expected only c or w"; exit 1;;
    esac
done
echo $result
