#!/usr/bin/env bash

# works fine, but not ideal
# also, **incredibly** slow for longer (100+) words.

fusage()
{
    echo "Usage: $(basename "$0") MASK"
    echo ""
    echo "$(basename "$0") creates a user-defined sequence of consonants and"
    echo "wovels. It can be used for generating random usernames and passwords."
    echo ""
    echo "MASK is a string of c a w: e.g. cwccwccwcwcwc"
    echo "c is replaced with a random consonant, w with a random wovel."
}

# Picks a random letter from $1.
pickfrom()
{
    echo "${1:$((RANDOM % ${#1})):1}"
}

wovels="aeiouy"
consonants="bcdfghjklmnpqrstvwxz"
mask="$1"
result=""

case "$mask" in
    '') fusage; exit 1;;
    -h|--help) fusage; exit 0;;
esac

for (( i=0; i<${#mask}; i++)); do
    byte="${mask:$i:1}"
    case $byte in
        c) result="$result$(pickfrom "$consonants")";;
        w) result="$result$(pickfrom "$wovels")";;
        *) echo "Invalid letter, expected only c or w"; exit 1;;
    esac
done
echo "$result"
