#!/bin/sh
cleanup() {
    kdesu -c "killall openvpn"
}

kdesu -c "openvpn --config $HOME/scripts/muni-main-linux.ovpn --auth-user-pass $HOME/scripts/secrets/muni-openvpn-user-pass &"
matlab

trap cleanup EXIT
