#!/bin/bash
set -euo pipefail

# shellcheck disable=SC2068 # Is there a better way to pass nothing or -s, in a simple way?
(date "+%Y-%m-%d_%H%M%S" \
    | dmenu -p "Choose a screenshot name, or pick the date." \
    | xargs -I{} maim $@ "$HOME/pic/sshot/{}.png") \
    && notify-send "scrot" "Screenshot created in $HOME/pic/sshot."
