#!/usr/bin/env bash
set -euo pipefail


usage() {
    echo "usage: $0 [-sh] [-O dirname] [-o basename]"
    echo "-s: maim region select"
    echo "-i: pick name after capture"
    echo "-n: notify-send after capture"
    echo "-o: dir name (default $_dirname)"
    echo "-O: base name (default current time, $_basename)"
    echo "-h: help"
}

main() {
    _dirname="$(xdg-user-dir PICTURES)/sshot"; local _dirname
    _basename="$(date "+%Y-%m-%d_%H%M%S")"; local _basename
    local maimopts=""
    local interactive=""
    local do_notify=""

    while getopts "o:O:ishn" opt; do
        case "$opt" in
            O) _dirname="$OPTARG";;
            o) _basename="$OPTARG";;
            s) maimopts="-s ";;
            h) usage; exit 0;;
            i) interactive="true";;
            n) do_notify="true";;
            *) usage; exit 1;;
        esac
    done

    fullname="${_dirname}/${_basename}.png"

    # shellcheck disable=2086
    maim --hidecursor --highlight --color=0.3,0.4,0.6,0.7 $maimopts "$fullname"

    if [ -n "$interactive" ]; then
        while true; do
            newname="$(dmenu-provider -p "Choose a screenshot name, or keep it as current date." <<< "$_basename")"
            [ -f "${_basename}/${newname}.png" ] || break;
            notify-send "$0" "File ${_basename}/${newname}.png already exists."
        done
        mv "${_dirname}/${_basename}.png" "${_dirname}/${newname}.png"
        _basename="$newname"
    fi

    if [ -n "$do_notify" ]; then
        notify-send -i "${_dirname}/${_basename}.png" "$0" "Screenshot ${_basename}.png created in ${_dirname}."
    fi

}

main "$@"
