#!/bin/sh
fwarn()
{
    notify-send -u critical \
        "Unfortunately, the clock is ticking" \
        "The hours are passing by. The past increases, the future recedes. Possibilities decreasing, regrets mounting."
        
}

while true; do
    sleep 5
    val=$RANDOM
    [ "$val" -le 3 ] && fwarn
done
