#!/usr/bin/env python3

"""
Logs in to a stupid dormitory router without having to open the landing page and
clicking "OK" and being redirected to stupid google.cz, ignoring the url I
wanted to go to in the first place.

First, it scrapes salt strings from the website, unescapes them and sends a POST with the username and the md5 password hash (imagine using md5 in 2022 LOL).

Shoutout to Wireshark for helping to get the headers right.

Anti-shoutout to requests.post() which refuses to send the text without parsing
everything into a dictionary first. Even then, the sent packet doesn't even
contain "POST /xxx HTTP/1.1"!
"""

import requests
import sys
import re
from hashlib import md5
import subprocess
import time


URL = r"http://192.168.4.1/login"
USERNAME = "sebela"
with open("wpassword") as f:
    pwstr = "".join(f.readlines()).rstrip("\n")
    PASSWORD = bytes(pwstr, encoding="utf-8")


headers=[
    "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0",
    "Accept: text/html,application/xhtml+xml,application/xml,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language: cs,sk;q=0.8,en-US;q=0.5,en;q=0.3",
    "Accept-Encoding: gzip, deflate",
    "Content-Type: application/x-www-form-urlencoded",
    "Content-Length: 73",
    "Origin: http://192.168.4.1",
    "DNT: 1",
    "Connection: keep-alive",
    "Referer: http://192.168.4.1/login?",
    "Upgrade-Insecure-Requests: 1"
]


dummy_data="username=sebela&password=b2506f213502ff7d789cad682bab6862&dst=&popup=true"


def octal_to_bytes(bytes_octal):
    _bytes = []
    for i in range(0, len(bytes_octal), 4):
        byte_octal = bytes_octal[i+1:i+4]
        byte = int(byte_octal, 8)
        _bytes.append(byte)
    return bytes(_bytes)


def unescape(s):
    return s.replace("\\\\", "\\")


def scrape_salt(content):
    # gets doubly escaped after requests.get for some 
    # reason, literally no docs about it
    pattern = r"hexMD5\(\\'([\\0-9]*)\\'.*\\'([\\0-9]*)\\'\)"
    matches = re.findall(pattern, str(content))[0]

    salt1 = bytes(unescape(matches[0]), encoding="ascii")
    salt1 = octal_to_bytes(salt1)
    assert len(salt1) == 1
    salt2 = bytes(unescape(matches[1]), encoding="ascii")
    salt2 = octal_to_bytes(salt2)
    return (salt1, salt2)


def compute_pwhash(pw, salt):
    salt1, salt2 = salt
    for x in [salt1, pw, salt2]:
        assert type(x) == bytes
    return md5(salt1 + pw + salt2).hexdigest()
    

def login(username, pwhash):
    global dummy_data

    data = dummy_data.replace("sebela", username)
    data = data.replace("b2506f213502ff7d789cad682bab6862", pwhash)
    args = ["curl", "-X", "POST", "--data", str(data)]
    for h in headers:
        args.append("-H")
        args.append(h)
    args.append(URL)
        
    curl = subprocess.run(args, capture_output=True)

    if b"You are logged in" in curl.stdout:
        print("[SUCCESS] Logged in :)")
        return 0
    elif b"invalid username or password" in curl.stdout:
        print("[ERROR] bad password :(")
        return 1
    else:
        print("[ERROR] Neither correct nor incorrect?")
        return 2
    

def main():
    resp = requests.get(URL)
    if resp.status_code == 200:
        print("[OK] Server sent salts")
    else:
        print("[ERROR] \n" + str(resp.content))
        return 1
    
    if b"You are logged in" in resp.content:
        print("[OK] Already logged in")
        return 0

    salt = scrape_salt(resp.content)
    print("[debug] Got salts: " + str(salt))

    pwhash = compute_pwhash(PASSWORD, salt)
    print("[debug] Hashed: " + pwhash)

    return login(USERNAME, pwhash)


if __name__ == "__main__":
    sys.exit(main())
