#!/usr/bin/env bash
#this is currently broken

root="/tmp/neumann"


neumann-rec()
{
    count=$1 
    for i in $(seq 0 $[$count-1]); do
        echo $i
        [ -d "$root/$i" ] && { ln -s "$root/$i" "$i"; continue; }
        mkdir -p $i
        pushd $i
        neumann-rec $i
        popd
    done 
}


main()
{
    mkdir -p $root && pushd $root
    
    count=$1
    [ $count -eq $count ] || { echo "Not a number, bye" >&2; exit 1; }
    neumann-rec $count

    popd
}

[ -z "$1" ] && {
    echo -e "usage: $0 LEVEL\ncreates /tmp/neumann with ordinals from symlinks up to LEVEL";
    echo -e "currently broken.";
    exit 0;
}
main $1
