#!/bin/bash

on_rpi()
{
	uname -n | grep -q rpi
}

# A great puzzle, after running this as sudo.
whointheworldami() 
{
	on_rpi && echo "$piusername" || echo "$pcusername"
}

################################################
#   configurable global settings / defaults    #
################################################

### MEASUREMENT ###
def_measure_time_seconds=30
def_mtu=1500
samplerate=990
# eventperiod=40000

# choose how to sample: -F samples all events at the same speed, might be more cpu intensive,  -c samples once per X events
howtosample="-F $samplerate"
# howtosample="-c $eventperiod"

### DEVICES ### 
pcaddr=169.254.1.1
pcusername="karel"
piaddr=169.254.2.2
piusername="rpi"

### PATH ###
# of the binary
uv="/home/$(whointheworldami)/zmisc/git-repos/UltraGrid/ug-myfork/bin/uv"
# of the test file
uvviddir="/home/$(whointheworldami)/vid/ugvid/y4m"
uvfilersg=ReadySetGo_1920x1080_120fps_420_8bit_YUV.y4m
uvfile="${uvviddir}/${uvfilersg}"
#######################################################


where_to_send_to()
{
	islocal="$1"
	if on_rpi; then
		if [ -n "$islocal" ]; then
			echo "$piaddr"
		else
			echo "$pcaddr"
		fi
	else
		if [ -n "$islocal" ]; then
			echo "$pcaddr"
		else
			echo "$piaddr"
		fi
	fi
}

# pi cannot record LLC misses
if on_rpi; then
	# shellcheck disable=SC2089
	whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses}:ppp'"
else
	# shellcheck disable=SC2089
	whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses,LLC-load-misses}:ppp'"
fi

perfrecord="sudo perf record $howtosample $whattosample  --call-graph dwarf,2048 --mmap-pages 16M -z --sample-cpu -o perf.data --"

i_am_not_root()
{
	[ $EUID != 0 ]
}

usage()
{ 
	echo "usage: $0 [-gvnNhl] [-t time] [-m mtu] [file|rtdxt|screen|logo|text|network|...] [extra UG args...]"
	echo "calls UltraGrid with arguments for the given scenario."
	echo "When recording between two devices, use:"
	echo "        \"$(basename $0) SCENARIO\"  on sender,"
	echo "        \"$(basename $0) receive\"   on receiver."
	echo ""
	echo "-g      use gdb instead of perf"
	echo "-v      use valgrind instead of perf"
	echo "-n      use nothing, only print the command"
	echo "-N      run UltraGrid, but don't use perf at all"
	echo "-h      help"
	echo "-l      send to localhost instead of to remote"
	# echo "-s      uv -d sdl"
	echo "-t N    run for N seconds (default $def_measure_time_seconds)"
	echo "-m MTU  MTU size (default $def_mtu) (aliases: himtu/jumbo/9k for 9000, lomtu/1k5 for 1500)"
}

main() 
{
	out="$(where_to_send_to)"
	possibly_noop=""
	pr="$perfrecord"

	measure_time_seconds="$def_measure_time_seconds"

	# XXX: run the command on rpi indefinitely by default, because I cannot
	# measure on it anyway and I don't want it to quit prematurely.
	# (Pretend it is always broadcasting or always receiving the data.) 
	# If both devices were traced, both devices would have the same timeout.
	on_rpi && measure_time_seconds=100000000

	
	mtu="$def_mtu"

	while getopts "gvnNhlt:m:" opt; do
		case "$opt" in
			g) pr="gdb --args";;
			v) pr="valgrind --track-origins=yes";;
			n) possibly_noop=":";;                     # : command does nothing
			N) pr=""; measure_time_seconds="10000000";;   # not measuring, pointless to timeout
			h) usage; exit 0;;
			l) out="$(where_to_send_to local)";;
			t) measure_time_seconds="$OPTARG";;
			m) mtu="$OPTARG";;
			# s) out="-d sdl";;
			*) usage; exit 1;;
		esac
	done
	shift $((OPTIND-1))

	case "$mtu" in
		himtu|9k)  mtu=9000;;
		lomtu|1k5) mtu=1500;;
		""|*[!0-9]*) echo "mtu is not a number"; exit 1;;
	esac

	# If we're measuring for real, set the perf command	
	
	possibly_elevate=""
	[[ "$pr" =~ "perf" && -z "$possibly_just_echo" && -n "$*" ]] && {
		pr="timeout $measure_time_seconds $perfrecord"
		possibly_elevate="sudo -n"
	}

	[ -z "$1" ] && { usage; exit 1; }
	scenario="$1"
	shift

	case "$scenario" in
		receive|receiver|recv)
			cmd="$pr $uv -d sdl:display=0 $*";
			:;;
		vulkan|vulk)
			cmd="$pr $uv -d vulkan_sdl2 $*";
			:;;
		file)  # uvfile + libavcodec (mjpeg)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec $* $out";
			:;;
		rtdxt|dxt) # uvfile + rtdxt
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c rtdxt:dxt1 $* $out";
			:;;
		screen) # screengrab + libavcodec
			cmd="$pr $uv -m $mtu -t screen:fps=60 -c libavcodec $* $out";
			:;;
		network|net) # testcard
			cmd="$pr $uv -m $mtu -t testcard:fps=1000 -d dummy  $* $out";
			:;;
		# deinterlace|deint) # uvfile + libavcodec + deinterlace
		# 	# this is file + deinterlace
		# 	echo "not figured out what to write"; exit 1;
		# 	cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec - -d dummy $out";
		# 	:;;
		testcardunc|tcunc)
			cmd="$pr $uv -m $mtu -t testcard:fps=60 $* $out";
			:;;
		testcard|tc)
			cmd="$pr $uv -m $mtu -t testcard:fps=60 -c libavcodec:encoder=mjpeg_qsv $* $out";
			:;;
		text|txt)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec -F text:x=10:y=1:h=100:t=A_sample_text $* $out";
			:;;
		textmid|txtm)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec -F text:x=500:y=500:h=100:t=A_sample_text $* $out";
			:;;
		# logo|lg) # uvfile + libavcodec + logo
		# 	cmd="$pr $uv -m $mtu -t testcard:fps=120 -c libavcodec -F logo:$HOME/pic/uglogo.pam $out";
		# 	# cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -F logo:pic/uglogo.pam -F text:x=10:y=800:h=100:t=A_sample_text $out";
		# 	:;;
		*) usage; exit 1;;
	esac

	echo "THE FULL COMMAND IS: \"$possibly_elevate $cmd\""

	# intentionally unquoted
	[[ -z "$possibly_noop" && -n "$possibly_elevate" ]] && i_am_not_root && { 
		echo "perf needs to be run as root"; exit 1;
	}

	$possibly_noop $possibly_elevate $cmd

	# if I timeouted, everything is okay.
	[ "$?" == 124 ] && true || false
}

main "$@"
