#!/bin/bash

### settings: adjust these ###
measuretime=30
samplerate=100
# samplerate=980
eventperiod=10000
### ---------------------- ####


# two options: X times per second, or once every X events
howtosample="-F $samplerate"
# howtosample="-c $eventperiod"

on_rpi()
{
	uname -n | grep rpi
}

if on_rpi; then
	# pi cannot record LLC misses
	whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses}:ppp'"
else
	whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses,LLC-load-misses}:ppp'"
fi

perfrecord="sudo perf record $howtosample $whattosample  --call-graph dwarf,2048 --mmap-pages 16M -z --sample-cpu --"
uv="$HOME/zmisc/git-repos/UltraGrid/ug-myfork/bin/uv"
# uv="/home/karel/uv"

piaddr=169.254.2.2
uvviddir=$HOME/vid/ugvid/y4m
uvfilersg=ReadySetGo_1920x1080_120fps_420_8bit_YUV.y4m
uvfile="${uvviddir}/${uvfilersg}"


checkforroot()
{
	[ $EUID = 0 ] || { echo "perf requires root to start"; exit 1; }
}

usage()
{ 
	echo "usage: $0 [-nNvgl] [file|rtdxt|screen|logotext|network|...] [MTU]"
	echo "calls UltraGrid with arguments for the given scenario."
	echo "-n   only print the command to be executed"
	echo "-N   only run UltraGrid, do not use  perf record"
	echo "-v   valgrind instead of profiling"
	echo "-g   gdb instead of profiling"
	echo "-l   don't send the video to rpi, display it locally on sdl screen"
	echo "MTU: himtu, 9000, 9k  sets it to 9000"
	echo "     lomtu, 1500, 1k5 sets it to 1500"
}

main() 
{
	out="$piaddr"
	possibly_just_echo=""
	
	pr="$perfrecord"

	while getopts "hnNvglt:" opt; do
		case "$opt" in
			t) measuretime=$OPTARG;;
			n) possibly_just_echo="echo";;
			N) pr="";;
			v) pr="valgrind --track-origins=yes";;
			g) pr="gdb --args";;
			l) out="-d sdl";;
			h) usage; exit 0;;
		esac
	done
	shift $((OPTIND-1))

	# I really requested perf
	# noop is not set

	possibly_elevate=""
	[[ "$pr" =~ "perf" && -z "$possibly_just_echo" && -n "$@" ]] && {
		pr="timeout $measuretime $perfrecord"
		possibly_elevate="sudo"
	}

	[ -z "$1" ] && { usage; exit 1; }
	

	mtu=1500
	case "$2" in
		himtu|9000|9k) mtu=9000;;
		lomtu|1500|1k5) mtu=1500;;
	esac

	case "$1" in
		receive)
			cmd="$pr $uv -d sdl";;
		file)  # uvfile + libavcodec (mjpeg)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec $out";
			:;;
		rtdxt) # uvfile + rtdxt
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c rtdxt:dxt1 $out";
			:;;
		screen) # screengrab + libavcodec
			cmd="$pr $uv -m $mtu -t screen:fps=60 -c libavcodec $out";
			:;;
		network|net) # testcard
			cmd="$pr $uv -m $mtu -t testcard:fps=1000 -d dummy $out";
			:;;
		deinterlace|deint) # uvfile + libavcodec + deinterlace
			# this is file + deinterlace
			echo "not figured out what to write"; exit 1;
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec - -d dummy $out";
			:;;
		logotext|lt) # uvfile + libavcodec + logo + text
			cmd="$pr $uv -m $mtu -t testcard:codec=RGBA -F logo:pic/uglogo.pam -F text:x=10:y=1:h=100:t=Ã_lazy_example_text $out";
			# cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -F logo:pic/uglogo.pam -F text:x=10:y=800:h=100:t=ÃǍ_lazy_example_text $out";
			:;;
		*) usage; exit 1;;
	esac

	# echo "cmd is:"
	# echo "$cmd"

	# necessary to split args, sadly breaks spaces

	$possibly_just_echo $possibly_elevate $cmd

}

main "$@"
