#!/bin/sh

#[ "$1" = "-r" ] && { possible_redirect=">/var/tmp/bpio"; shift; }

iof=/var/tmp/bpio
netf=/var/tmp/bpnet
datecmd="date --iso-8601=seconds"

getio()
{
   # (01-07) device            r/s rKB ???x4 
   # (08-19) w/s wkB/s ???x4   d/s? dKB%s? ???x4
   # (20-23) f/s f_await aqu-sz %util

   # asi fajn je   rKB/s ($4)     %util ($23)
   # +1 for date

   iostat -xz 1 |\
      stdbuf -o0 grep nvme0n1 |\
      prepend_seconds_since_start |\
      stdbuf -o0 awk '{print $1, $4, $24}' >$iof
}

starttime=$(date +"%s")
prepend_seconds_since_start()
{
	while read n; do \
		echo "$(($(date +%s) - starttime)) $n"; \
	 done
}


getnet()
{
	 #   1                4                                  11
	 # date iface rxpck txpck rxkB txkB rxcmp txcmp rxmcst %ifutil

	 sar -n DEV 1 |
	    stdbuf -o0 grep wlan0 |\
	    prepend_seconds_since_start |\
	    stdbuf -o0 awk '{print $1, $5, $12}' >$netf
}


collectboth() {
	pkill getio
	pkill getnet
	sort $iof  | sed "s/[[:space:]]\+/,/g" > ${iof}_s
	sort $netf | sed "s/[[:space:]]\+/,/g" > ${netf}_s
	
	# echo "---------bpios---------"
	# cat ${iof}_s
	# echo "---------bpnets--------"
	# cat ${netf}_s
	# echo "---------both----------"
	echo "second #,tx pck/s,net util,read KB,io util"
	join -t , -a 1 -a 2 -e 0.00 -o auto ${netf}_s ${iof}_s
}

# wipe them
:>${iof}
:>${netf}
:>${iof}_s
:>${netf}_s

# run them both
getio&
getnet&

trap collectboth INT
trap collectboth TERM
sleep 60
