#!/bin/sh

#[ "$1" = "-r" ] && { possible_redirect=">/var/tmp/bpio"; shift; }

iof=/var/tmp/bpio
netf=/var/tmp/bpnet
datecmd="date --iso-8601=seconds"

getio()
{
   # device            r/s rKB ???x4 
   # w/s wkB/s ???x4   d/s? dKB%s? ???x4
   # f/s f_await aqu-sz %util

   # asi fajn je 
   # wKB/s ($8)
   # %util ($22)
   # +1 for date

   iostat -xz 1 |\
      stdbuf -o0 grep nvme0n1 |\
      stdbuf -o0 sed "s/^/$($datecmd)  /" |\
      stdbuf -o0 awk '{print $1, $9, $23}' >$iof
}


getnet()
{
	 #   1              4                                         11
	 # date avg iface rxpck txpck rxkB txkB rxcmp txcmp rxmcst %ifutil
	 sar -n DEV 1 |\
	    stdbuf -o0 grep wlan0 |\
	    stdbuf -o0 sed "s/^/$($datecmd)  /" |\
	    stdbuf -o0 awk '{print $1, $4, $11}' >$netf
}


collectboth() {
	pkill getio
	pkill getnet
	sort $iof > ${iof}_s
	sort $netf > ${netf}_s
	
	echo "---------bpios---------"
	cat ${iof}_s
	echo "---------bpnets--------"
	cat ${netf}_s
	join ${iof}_s ${netf}_s
}

>${iof}
>${netf}
>${iof}_s
>${netf}_s
getio&
getnet&
trap collectboth SIGINT

sleep 10000
