#!/bin/sh
# takes like 10 mins only
# rsync -Pruv pi:/usr piroot

rsync -PruvL pi:perf.data pi:kallsyms .
rsync -PruvL pi:uv bin/uv
# swallow hotspot --kallsyms kallsyms --extraLibPaths ./bin:./piroot/usr/lib/aarch64-linux-gnu --sysroot piroot perf.data
swallow hotspot --kallsyms kallsyms --extraLibPaths ./bin --sysroot piroot --debugPaths ./piroot/usr/lib/debug/.build-id perf.data
# hotspot --kallsyms kallsyms --appPath uv --sysroot piroot/usr perf.data
