#!/bin/bash
set -euo pipefail

this_device_is_my_own_laptop()
{
	uname -n | grep -q arch0
}

this_device_is_a_school_desktop_machine()
{
	uname -n | grep -q "^hd[1-8]$"
}

whointheworldami()
{
	if this_device_is_my_own_laptop; then
		echo "karel"
	elif this_device_is_a_school_desktop_machine; then
		uname -n
	else
		echo "whointheworldami: Unreachable"
		exit 1;
	fi
}

################################################
#   configurable global settings / defaults    #
################################################


#### MEASUREMENT ####
def_measure_time_seconds=60
def_mtu=1500


#### SAMPLING ####
##  -F samples all events at the same speed
##		might be more cpu intensive
##  -c samples once per X events 
samplerate=990
# eventperiod=40000
howtosample="-F $samplerate"
# howtosample="-c $eventperiod"


#### BINARY PATH ####
## can't rely on $HOME when I'm running as root but the binaries
## are elsewhere. Use hostname instead.
uv_path_on_my_machines="/home/$(whointheworldami)/zmisc/git-repos/UltraGrid/ug-myfork/bin/uv"
uv_path_on_hd_machines="/home/$(whointheworldami)/UltraGrid-continuous-x86_64.AppImage"
uv_viddir_on_my_machines="/home/$(whointheworldami)/vid/ugvid/y4m";
uv_viddir_on_hd_machines="/home/$(whointheworldami)/ug-benchmarks";

#### VIDEO PATH ####
uv_test_video_filename="ReadySetGo_1920x1080_120fps_420_8bit_YUV.y4m"


if this_device_is_my_own_laptop; then
	uv_path="$uv_path_on_my_machines";
	uv_viddir="$uv_viddir_on_my_machines";
elif this_device_is_a_school_desktop_machine; then
	uv_path="$uv_path_on_hd_machines";
	uv_viddir="$uv_viddir_on_hd_machines";
else
	echo "Unreachable"; exit 1;
fi

###################################################
#   configurable global settings / defaults  end  #
###################################################

uv="$uv_path"
uvfile="${uv_viddir}/${uv_test_video_filename}"

## pi cannot record LLC misses (commented because unused)
# if on_rpi; then
	# shellcheck disable=SC2089
	# whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses}:ppp'"
# else
	# shellcheck disable=SC2089
	whattosample="-e '{cycles,branch-misses,L1-dcache-load-misses,LLC-load-misses}:ppp'"
# fi

perfrecord="sudo -n perf record $howtosample $whattosample  --call-graph dwarf,2048 --mmap-pages 16M -z --sample-cpu -o perf.data --"

i_am_not_root()
{
	[ $EUID != 0 ]
}

usage()
{ 
	echo "usage: $0 [-gvnNhl] [-t time] [-m mtu] [sendfile|senddxt|sendscreen|sendlogo|recvtext|looplimits|...] [extra UG args...]"
	echo "calls UltraGrid with arguments for the given scenario."
	echo ""
	echo "When recording between two devices, use:"
	echo "        \"$(basename "$0") sendXXX\"     on sender,"
	echo "        \"$(basename "$0") recvXXX\"     on receiver."
	echo "The exception is the  limits  scenario where nothing is sent out:"
	echo "        \"$(basename "$0") looplimits\"  on a local computer"
	echo ""
	echo "-g      use gdb instead of perf"
	echo "-v      use valgrind instead of perf"
	echo "-n      use nothing, only print the command"
	echo "-N      run UltraGrid, but don't use perf at all"
	echo "-h      help"
	echo "-l      send to localhost instead of to remote"
	echo "-t N    run for N seconds (default $def_measure_time_seconds)"
	echo "-m MTU  MTU size (default $def_mtu) (aliases: himtu/jumbo/9k for 9000, lomtu/1k5 for 1500)"
}

main() 
{
	possibly_noop=""

	out="localhost"  # XXX: for now
	pr="$perfrecord"

	measure_time_seconds="$def_measure_time_seconds"

	mtu="$def_mtu"

	while getopts "gvnNhlt:m:" opt; do
		case "$opt" in
			g) pr="gdb --args";;
			v) pr="valgrind --track-origins=yes";;
			n) possibly_noop=":";;                     # : command does nothing
			N) pr=""; unset measure_time_seconds;;   # not measuring, pointless to timeout
			h) usage; exit 0;;
			l) out="-d sdl $(where_to_send_to local)";;
			t) measure_time_seconds="$OPTARG";;
			m) mtu="$OPTARG";;
			# s) out="-d sdl";;
			*) usage; exit 1;;
		esac
	done
	shift $((OPTIND-1))

	case "$mtu" in
		himtu|9k)  mtu=9000;;
		lomtu|1k5) mtu=1500;;
		""|*[!0-9]*) echo "mtu is not a number"; exit 1;;
	esac	
	
	need_root=""
	[[ "$pr" =~ "perf" && -n "$*" ]] && {
		need_root=yes
		pr="timeout $measure_time_seconds $perfrecord"
	}

	if  [ -z "${1:-}" ]; then
		 usage; exit 1;
	else
		true;
	fi
	scenario="$1"
	shift

	case "$scenario" in
		recvsdl)
			cmd="$pr $uv -d sdl:display=0 $*";
			:;;
		recvvulkan|recvvulk)
			cmd="$pr $uv -d vulkan_sdl2:display=0 $*";
			:;;
		sendfile)  # uvfile + libavcodec (mjpeg)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec $* $out";
			:;;
		sendfilenodec|sendfilenodecode)  # uvfile + libavcodec (mjpeg)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop:nodecode -c libavcodec $* $out";
			:;;
		sendrtdxt|senddxt) # uvfile + rtdxt
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c rtdxt:dxt1 $* $out";
			:;;
		sendscreen) # screengrab + libavcodec
			cmd="$pr $uv -m $mtu -t screen:fps=120 -c libavcodec $* $out";
			:;;
		looplimits|looplim) # dumb testcard
			cmd="$pr $uv -m $mtu -t testcard:fps=1000 -d dummy  $*";
			:;;
		# deinterlace|deint) # uvfile + libavcodec + deinterlace
		# 	# this is file + deinterlace
		# 	echo "not figured out what to write"; exit 1;
		# 	cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec - -d dummy $out";
		# 	:;;

		# sendtestcardunc|sendtcunc)
		# 	cmd="$pr $uv -m $mtu -t testcard:fps=60 $* $out";
		# 	:;;
		# sendtestcard|sendtc)
		# 	cmd="$pr $uv -m $mtu -t testcard:fps=60 -c libavcodec:encoder=mjpeg_qsv $* $out";
		# 	:;;
		sendtext|sendtxt)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec -F text:x=10:y=1:h=100:t=A_sample_text $* $out";
			:;;
		sendtextmid|sendtxtm)
			cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -c libavcodec -F text:x=500:y=500:h=100:t=A_sample_text $* $out";
			:;;
		# logo|lg) # uvfile + libavcodec + logo
		# 	cmd="$pr $uv -m $mtu -t testcard:fps=120 -c libavcodec -F logo:$HOME/pic/uglogo.pam $out";
		# 	# cmd="$pr $uv -m $mtu -t file:${uvfile}:loop -F logo:pic/uglogo.pam -F text:x=10:y=800:h=100:t=A_sample_text $out";
		# 	:;;
		*) usage; exit 1;;
	esac

	echo "THE FULL COMMAND IS:"
	echo "--------------------"
	echo "$cmd"
	echo "--------------------"

	# intentionally unquoted
	[[ -z "$possibly_noop" && -n "$need_root" ]] && i_am_not_root && { 
		echo "perf needs to be run as root"; exit 1;
	}

	# (possible) sudo is already used inside cmd
	$possibly_noop $cmd ||  ( 
		# If I timed out, everything is okay, don't fail.
		[ "$?" == 124 ]
	) 
}

main "$@"
