#!/bin/sh
set -euo pipefail
remote="rpi@169.254.2.2"
username=karel

end_remote_tracing()
{
    sudo -u "$username" ssh -f "$remote" killall dothetest
}

sendfn()
{
    mkdir -p pctopi/$1
    pushd pctopi/$1

    # [ -f perf.data ] && { echo "A record for $1 already exists."; exit 0; }

    sudo -u "$username" ssh -f "$remote" scripts/bp/dothetest receive | tee remote-stdout
    dothetest $1  | tee local-stdout
    end_remote_tracing

    grep FPS local-stdout | ug-extractfps | awk '{ s+=$1; n++ } END { print s/n }' >average-fps-local
    grep FPS remote-stdout | ug-extractfps | awk '{ s+=$1; n++ } END { print s/n }' >average-fps-remote
}

recvfn()
{
    mkdir -p pitopc/$1
    cd pitopc/$1

    sudo -u "$username" ssh -f "$remote" scripts/bp/dothetest $1 | tee remote-stdout
    dothetest receive | tee local-stdout
    sudo -u "$username" ssh -f "$remote" killall dothetest

    grep FPS local-stdout | ug-extractfps | awk '{ s+=$1; n++ } END { print s/n }' >average-fps-local
    grep FPS remote-stdout | ug-extractfps | awk '{ s+=$1; n++ } END { print s/n }' >average-fps-remote
}

[ $EUID = 0 ] || { echo "perf requires root to start"; exit 1; }

case "$(basename $0)" in
    send) sendfn "$@";;
    receive) recvfn "$@";;
esac

trap end_remote_tracing INT
end_remote_tracing
