#!/bin/bash
# ideas from here:
# https://codereview.stackexchange.com/questions/174019/ps1-for-bash-prompt-showing-last-exit-status-written-mostly-in-python


RET=$?
echo $RET
CHROOT='${debian_chroot:+($debian_chroot)}'
e='\033'
GREEN="\[$e[1;32m\]"
YELLOW="\[$e[1;33m\]"
BLUE="\[$e[1;34m\]"
RESET="\[$e[0m\]"
[ $RET -eq 0 ] && NAME_COL=$GREEN || NAME_COL=$YELLOW;
USERNAME='\u'
HOSTNAME='\h'
WORKDIR_FULL='\w'
WORKDIR_SHORT='\W'
echo "PS1 is now this"
line="${CHROOT}${NAME_COL}${USERNAME}@${HOSTNAME}${RESET}:"
linetwo="${BLUE}${WORKDIR_SHORT}{$RESET}$ "
echo "$line$linetwo"
PS1="$line$linetwo"

