#!/bin/sh
# query website from command line, read json response in less

query=$(echo "$1" | internal/urlenc)

bn=$(basename "$0")
case $bn in
    jisho) url="https://jisho.org/api/v1/search/words?keyword=$query";;
    endict) url="https://api.dictionaryapi.dev/api/v2/entries/en/$query";;
    *) echo "$bn expected to be run from a symlink context. To add a new dictionary, make a symlink and add a case entry inside $0.">&2; exit 1;;
esac

curl "$url" 2>/dev/null | jq --color-output | less -R
