#!/bin/bash

fentry()
{
    # $1 is either:
    case $1 in
        '') days_back=0;;               # nothing  -> edit with current date
        -*) days_back=${1#"-"};;        # -NUMBER  -> edit NUMBER days in past
        *) vim + "$D/$1.md"; return;;   # filename -> edit filename
    esac
    
    echo $days_back | egrep '^[0-9]*$' >/dev/null || \
        { echo "Expected number of days into past (try -1 or -30)"; exit 1; }

    curdate=$(date -I --date="@$[$(date +%s)-86400*$days_back]");   # format stuff into ISO-8601
    filename=$curdate.md
    vim + "$D/$filename"
}

flist_dir()
{
    ls "$D"
}


NOTEROOT=$(ptpath)

case "$1" in
    yume) D=$NOTEROOT/yume; shift;;
    food) D=$NOTEROOT/food; shift;;
    *) D=$NOTEROOT/Deník;;
esac

case "$1" in
    list)   flist_dir;;
    read)   true;;
    *)  fentry "$1";;
esac


