#!/usr/bin/env bash

#[ "$1" = "-r" ] && { possible_redirect=">/var/tmp/bpio"; shift; }

iof=/var/tmp/bpio
netf=/var/tmp/bpnet
gpuf=/var/tmp/bpgpu
datecmd="date --iso-8601=seconds"

getio()
{
	# (01-07) device            r/s rKB ???x4 
	# (08-19) w/s wkB/s ???x4   d/s? dKB%s? ???x4
	# (20-23) f/s f_await aqu-sz %util

	# asi fajn je   rKB/s ($4)     %util ($23)

	# io rKB, %util

	iostat -x 1 |\
		stdbuf -o0 grep nvme0n1 |\
		stdbuf -o0 awk '{print $3, $23}' |\
		prepend_seconds_since_start >$iof
}

starttime=$(date +"%s")
prepend_seconds_since_start()
{
	while read n; do \
		echo "$(printf "%.4d" "$(($(date +%s) - starttime))")" "$n"; \
	 done
}

getnet()
{
	 #   1                4                                  10
	 # date iface rxpck txpck rxkB txkB rxcmp txcmp rxmcst %ifutil

	 sar -n DEV 1 |
	    stdbuf -o0 grep wlan0 |\
	    stdbuf -o0 awk '{print $4, $10}' |\
	    prepend_seconds_since_start >${netf}
}

getgpu()
{
	 # Freq MHz      IRQ RC6     IMC MiB/s           RCS/0           BCS/0           VCS/0          VECS/0
	 # req  act       /s   %   pkg     rd     wr       %  se  wa       %  se  wa       %  se  wa       %  se  wa

	# the RC6 column is free time (100 idle, 0 loaded)
	intel_gpu_top -l |\
	    stdbuf -o0 grep -v -e "RC6\|%" |\
		stdbuf -o0 awk '{print 100-$4}' |\
		prepend_seconds_since_start >${gpuf}
}


collectall() {
	pkill getio
	pkill getnet
	pkill getgpu
	sort -n $iof  | sed "s/[[:space:]]\+/,/g" > ${iof}_s
	sort -n $netf | sed "s/[[:space:]]\+/,/g" > ${netf}_s
	sort -n $gpuf | sed "s/[[:space:]]\+/,/g" > ${gpuf}_s
	
	# echo "---------bpios---------"
	# cat ${iof}_s
	# echo "---------bpnets--------"
	# cat ${netf}_s
	# echo "---------both----------"
	echo "seconds,tx_pck,net_util,read_KB,io_util,gpu_util"
	# join  -t, -a1 -a2 -e 0.00 -o auto ${netf}_s ${iof}_s 
	join -t, -a1 -a2 -e 0.00 -o auto ${netf}_s ${iof}_s |\
		join -t, - ${gpuf}_s
}

[ "$EUID" -ne 0 ] && { echo "the gpu collection requires root"; exit 1; }

# wipe them
rm ${iof} ${netf} ${iof}_s ${netf}_s ${gpuf} ${gpuf}_s

# run them both
getio&
getnet&
getgpu&

trap collectall INT
trap collectall TERM
sleep 60
