#!/bin/sh

# takes like a minute
# rsync -Pruv pi:/usr piroot

ssh pi sudo cp /proc/kallsyms /home/rpi/kallsyms

rsync -PruvL pi:perf.data pi:kallsyms .
rsync -PruvL pi:uv bin/uv

swallow hotspot --kallsyms kallsyms --appPath ./bin --sysroot piroot --sourcePaths /home/karel/zmisc/git-repos/UltraGrid/ug-myfork/src perf.data

# swallow hotspot --kallsyms kallsyms --extraLibPaths ./bin --sysroot piroot perf.data

# this crashes idk why
# swallow hotspot --kallsyms kallsyms --extraLibPaths ./bin --sysroot piroot --debugPaths ./piroot/usr/lib/debug/.build-id perf.data
