#!/bin/bash

# DON'T USE
# This was some idea to setup i3 workspace names for everything
# Right now, this is broken and don't feel like developing it

ws1=1
ws2=2
ws3=3
ws4=4
ws5=5
ws6=6
ws7=7
ws8=8
ws9=9
ws10=10

do_the_setup()
{
	case "$1" in
		reset)
			i3-msg 'rename workspace $ws1 to 1'
			i3-msg 'rename workspace $ws2 to 2'
			i3-msg 'rename workspace $ws3 to 3'
			i3-msg 'rename workspace $ws4 to 4'
			i3-msg 'rename workspace $ws5 to 5'
			i3-msg 'rename workspace $ws6 to 6'
			i3-msg 'rename workspace $ws7 to 7'
			i3-msg 'rename workspace $ws8 to 8'
			i3-msg 'rename workspace $ws9 to 9'
			i3-msg 'rename workspace $ws10" to 10'

		thesis)
			i3-msg 'rename workspace $ws1 to todo'
			i3-msg 'rename workspace $ws2 to code'
			i3-msg 'rename workspace $ws3 to thesis'
			i3-msg 'rename workspace $ws4 to web'
			i3-msg 'rename workspace $ws5 to hotspot'
			i3-msg 'rename workspace $ws6 to measure'
			i3-msg 'rename workspace $ws7 to other'
			i3-msg 'rename workspace $ws8 to private'
			i3-msg 'rename workspace $ws9 to configs'
			i3-msg 'rename workspace $ws10" to 10'

			# i3-msg 'for_window [class="firefox"] move container to workspace "4 web"'
			# i3-msg 'for_window [class="firefox"] move container to workspace "4 web"'
			# i3-msg 'for_window [class="hotspot"] move container to workspace "5 hotspot"'
			# i3-msg 'for_window [title="quartus"] move container to workspace "dont care"'
			;;
		*) echo "$1 not matching"

	esac
}


main()
{
	options="thesis
personal usage
fgtp development"
	
	selection="$(echo "$options" | dmenu -p "What are you doing right now?")"

	grep "$selection" <<<"$options" && do_the_setup "$selection"

	case "$out" in
		thesis) 			do_the_setup "$out";;
		"personal usage") 	do_the_setup "$out";;
		"fgtp/development") do_the_setup "$out";;
		*) exit 1;;
	esac



}


echo "TODO"
# main "$@"
