#!/usr/bin/env bash

for arg in "$@"; do
	if [[ "$arg" = "-O2" || "$arg" = "-O3" ]]; then
		echo "You don't need more than -O1"
		result+="-O1 "
	else
		result+="$arg "
	fi
done

/usr/bin/gcc $result
