#!/bin/sh
notify-send -w create_ap "Dude, atheism is, like, the best religion, man. Everyone loves having an infinite recursion in your basis of moral truth and succumbing to the stupidest impulses, dude. Like, obviously, haha."
