#!/bin/sh
notify-send -t 0 "Etterna" \
"People almost don't know or care anymore that there's something to do with your attention, besides go on twitter and see -- or go on Hacker News or Reddit and see what people are talking about right this second. And the problem is ... done over years, that's going to damage your brain.

No exaggeration, it may have already damaged your brain.
"
