#!/bin/sh
outdir="$(xdg-user-dir VIDEOS)/recordings"

mkdir -p "$outdir"
file="${outdir}/$(date +%Y-%m-%d_%H%M%S).mp4"
notify-send "$0"  "Recording to $file using ffmpeg."

# hardware accel _qsv or _vaapi doesn't work, I don't know why
ffmpeg -f x11grab -i "$DISPLAY" -framerate 60 -c:v h264 "$file"
# ffmpeg -f x11grab -i "$DISPLAY" -framerate 60 -c:v h264_qsv "$file"
